### ISSUE TITLE
NameError: name 'CHAR_SET' is not defined

### ISSUE THREAD

**Issue by tbot1738** [zero-to-mastery/ascii-art-2022#47]
There is an error while converting image using webapp. It returns this error and I was not following along since a long tie so I dont know what is going on in the files. Please anyone review the error.
![image](https://user-images.githubusercontent.com/62806243/194959908-060d8a1c-c78f-4cdc-bc14-9e751e604c53.png)

**Comment by beneyal** [comment]
I'll reorganize the code in `community_version.py` a bit, that'll take care of the error too.

**Comment by tbot1738** [comment]
> I'll reorganize the code in `community_version.py` a bit, that'll take care of the error too.

Ok thanks Ben.
